"""webui-service 测试：配置视图/安全写入/切源动作/lx 校验回路/反代与二维码。

supervisorctl 与音源 HTTP 均离线：前者 monkeypatch，后者 MockTransport。
"""
from __future__ import annotations

import importlib.util
import sys
import time
from contextlib import contextmanager
from pathlib import Path

import httpx
import pytest
from fastapi.testclient import TestClient

HERE = Path(__file__).resolve().parent


def _load_webui():
    spec = importlib.util.spec_from_file_location("webui_service_app", HERE / "app.py")
    mod = importlib.util.module_from_spec(spec)
    sys.modules["webui_service_app"] = mod
    spec.loader.exec_module(mod)
    return mod


webui = _load_webui()

BASE_ENV = """# generated by install.sh — do not commit
FNMUSIC_NETEASE_ENABLED='true'
FNMUSIC_NETEASEFREE_ENABLED='false'
FNMUSIC_MUSICDL_ENABLED='false'
FNMUSIC_LX_ENABLED='false'
FNMUSIC_ONLINE_SOURCES='KuwoMusicClient'
MUSICDL_SOURCES='KuwoMusicClient'
LX_SOURCE_URL=''
FNMUSIC_QUALITY_MODE='high'
FNMUSIC_RECOMMEND_HOT='true'
FNMUSIC_RECOMMEND_DAILY='true'
FNMUSIC_TEE_SAVE_ENABLED='true'
FNMUSIC_TEE_CACHE_MAX='2'
CUSTOM_KEY='keepme'
"""


@pytest.fixture
def env_file(tmp_path, monkeypatch):
    env = tmp_path / ".env"
    env.write_text(BASE_ENV, encoding="utf-8")
    (tmp_path / "VERSION").write_text("2.0.0\n", encoding="utf-8")
    monkeypatch.setattr(webui, "ENV_PATH", env)
    monkeypatch.setattr(webui, "VERSION_PATH", tmp_path / "VERSION")
    webui._preview_until.clear()  # 预览状态是模块级全局，用例间隔离
    return env


@contextmanager
def authed_client():
    with TestClient(webui.app) as client:
        client.headers.update({"X-Trim-Isadmin": "true"})
        yield client


@pytest.fixture
def svctl(monkeypatch):
    calls: list[tuple] = []
    status_output = {
        "musicdl": "musicdl                        STOPPED   Not started",
        "musicbox": "musicbox                       RUNNING   pid 7, uptime 0:01:00",
        "lxmusic": "lxmusic                        STOPPED   Not started",
        "webui": "webui                          RUNNING   pid 8, uptime 0:01:00",
    }

    def fake(*args, timeout=20.0):
        calls.append(tuple(args))
        if args[0] == "status":
            # 真实 supervisorctl：存在 STOPPED 程序时退出码为 3（按需加载的常态）
            return 3, "\n".join(status_output.values())
        return 0, f"{args[0]}ed {args[1]}"

    monkeypatch.setattr(webui, "supervisorctl", fake)
    fake.calls = calls
    return fake


def _mock_http(handler):
    webui.app.state.http = httpx.AsyncClient(transport=httpx.MockTransport(handler))


# ------------------------------------------------------------------ 配置视图 ---

def test_config_view_merges_defaults(env_file):
    with authed_client() as client:
        r = client.get("/api/config")
        assert r.status_code == 200
        rj = r.json()
        assert rj["values"]["FNMUSIC_NETEASE_ENABLED"] == "true"
        assert rj["values"]["LX_SOURCE_URL"] == ""
        assert rj["values"]["FNMUSIC_LLM_MODEL"] == "kilo-auto/free"  # 缺省补齐（内置 Kilo）
        assert rj["values"]["FNMUSIC_LLM_PROVIDER"] == "kilo"  # 默认内置接入方
        assert "CUSTOM_KEY" not in rj["values"]  # 非管理键不进视图
        assert rj["schema"]["FNMUSIC_QUALITY_MODE"]["values"] == ["high", "balanced", "smooth"]
        # 分类歌单缺省补齐（.env 未写该键时给默认分类与曲量）
        assert rj["values"]["FNMUSIC_RECOMMEND_CATEGORIES"] == "华语,流行,摇滚,民谣,电子,古风,说唱,轻音乐,爵士"
        assert rj["values"]["FNMUSIC_RECOMMEND_CATEGORY_SIZE"] == "200"


def test_category_playlist_config_normalizes(env_file):
    norm = webui._normalize_value
    # 中英文逗号混用、去空白、去重
    assert norm("FNMUSIC_RECOMMEND_CATEGORIES", "华语，流行, 华语 ,电子") == "华语,流行,电子"
    # 留空即关闭分类歌单
    assert norm("FNMUSIC_RECOMMEND_CATEGORIES", "") == ""
    # 每类曲量收敛到 20-1000
    assert norm("FNMUSIC_RECOMMEND_CATEGORY_SIZE", "5") == "20"
    assert norm("FNMUSIC_RECOMMEND_CATEGORY_SIZE", "99999") == "1000"


# ------------------------------------------------------------------ PUT 校验 ---

def test_put_ignores_unknown_key(env_file):
    """未知键被忽略而非整单失败（兼容旧版前端提交的已下线键）。"""
    with authed_client() as client:
        r = client.put("/api/config", json={"values": {"NOT_A_KEY": "1"}})
        assert r.status_code == 200
        assert r.json()["ignored"] == ["NOT_A_KEY"]
        assert "NOT_A_KEY" not in env_file.read_text(encoding="utf-8")


def test_put_tolerates_deprecated_key(env_file):
    """回归：旧版前端仍提交 FNMUSIC_RECOMMEND_HOT 时，其余有效键照常保存。"""
    with authed_client() as client:
        r = client.put("/api/config", json={"values": {
            "FNMUSIC_RECOMMEND_HOT": True,
            "FNMUSIC_QUALITY_MODE": "smooth",
        }})
        assert r.status_code == 200, r.text
        body = r.json()
        assert "FNMUSIC_RECOMMEND_HOT" in body["ignored"]
        assert "FNMUSIC_QUALITY_MODE" in body["changed"]
    text = env_file.read_text(encoding="utf-8")
    assert "FNMUSIC_QUALITY_MODE='smooth'" in text
    # 已下线键既不被新增写入，也不参与本次更新（既有值原样保留）
    assert "FNMUSIC_RECOMMEND_HOT=" in text


def test_put_rejects_bad_enum(env_file):
    with authed_client() as client:
        r = client.put("/api/config", json={"values": {"FNMUSIC_QUALITY_MODE": "ultra"}})
        assert r.status_code == 400


def test_put_rejects_multi_provider(env_file):
    with authed_client() as client:
        r = client.put("/api/config", json={"values": {"FNMUSIC_LX_ENABLED": "true"}})
        assert r.status_code == 400
        assert "四选一" in r.json()["error"]


def test_put_rejects_zero_provider(env_file):
    with authed_client() as client:
        r = client.put("/api/config", json={"values": {"FNMUSIC_NETEASE_ENABLED": "false"}})
        assert r.status_code == 400
        assert "至少" in r.json()["error"]


# ------------------------------------------------------------------ 写入语义 ---

def test_put_hot_keys_roundtrip_preserves_custom(env_file):
    with authed_client() as client:
        r = client.put("/api/config", json={"values": {
            "FNMUSIC_QUALITY_MODE": "balanced",
            "FNMUSIC_RECOMMEND_DAILY": False,
            "FNMUSIC_TEE_CACHE_MAX": 5,
        }})
        assert r.status_code == 200
        rj = r.json()
        assert set(rj["changed"]) == {"FNMUSIC_QUALITY_MODE", "FNMUSIC_RECOMMEND_DAILY", "FNMUSIC_TEE_CACHE_MAX"}
        assert rj["actions"] == []
    text = env_file.read_text(encoding="utf-8")
    assert "FNMUSIC_QUALITY_MODE='balanced'" in text
    assert "FNMUSIC_TEE_CACHE_MAX='5'" in text
    assert "CUSTOM_KEY='keepme'" in text          # 用户自定义键保留
    assert "# generated by install.sh" in text     # 文件头保留
    assert env_file.with_name(env_file.name + ".webui.bak").exists()  # 写前备份
    assert env_file.with_name(env_file.name + ".webui.bak").stat().st_mode & 0o777 == 0o600  # 备份含密钥，与 .env 同权限


def test_put_noop_returns_empty_change(env_file):
    with authed_client() as client:
        r = client.put("/api/config", json={"values": {"FNMUSIC_QUALITY_MODE": "high"}})
        assert r.status_code == 200
        assert r.json()["changed"] == []


def test_search_timeout_defaults_and_saves(env_file):
    with authed_client() as client:
        view = client.get("/api/config")
        assert view.status_code == 200
        assert view.json()["values"]["FNMUSIC_SEARCH_TIMEOUT"] == "15"
        assert view.json()["values"]["FNMUSIC_SEARCH_PROBE"] == "false"
        saved = client.put("/api/config", json={"values": {"FNMUSIC_SEARCH_TIMEOUT": 9, "FNMUSIC_SEARCH_PROBE": True}})
        assert saved.status_code == 200
        assert "FNMUSIC_SEARCH_TIMEOUT" in saved.json()["changed"]
        assert "FNMUSIC_SEARCH_PROBE" in saved.json()["changed"]
    text = env_file.read_text(encoding="utf-8")
    assert "FNMUSIC_SEARCH_TIMEOUT='9'" in text
    assert "FNMUSIC_SEARCH_PROBE='true'" in text
    with authed_client() as client:
        again = client.get("/api/config")
        assert again.json()["values"]["FNMUSIC_SEARCH_TIMEOUT"] == "9"
        assert again.json()["values"]["FNMUSIC_SEARCH_PROBE"] == "true"
        clamped = client.put("/api/config", json={"values": {"FNMUSIC_SEARCH_TIMEOUT": 99}})
        assert clamped.status_code == 200
    assert "FNMUSIC_SEARCH_TIMEOUT='60'" in env_file.read_text(encoding="utf-8")


def test_put_int_clamps_and_bool_normalizes(env_file):
    with authed_client() as client:
        r = client.put("/api/config", json={"values": {"FNMUSIC_TEE_CACHE_MAX": 999}})
        assert r.status_code == 200
    assert "FNMUSIC_TEE_CACHE_MAX='100'" in env_file.read_text(encoding="utf-8")


def test_lyric_auto_dl_default_false_and_roundtrip(env_file):
    """自动下载歌词：默认关闭；开启后写回 .env，热重载键无需重启。"""
    with authed_client() as client:
        view = client.get("/api/config")
        assert view.status_code == 200
        assert view.json()["values"]["FNMUSIC_LYRIC_AUTO_DL"] == "false"
        assert view.json()["schema"]["FNMUSIC_LYRIC_AUTO_DL"]["reload"] == "hot"
        saved = client.put("/api/config", json={"values": {"FNMUSIC_LYRIC_AUTO_DL": True}})
        assert saved.status_code == 200
        assert "FNMUSIC_LYRIC_AUTO_DL" in saved.json()["changed"]
    assert "FNMUSIC_LYRIC_AUTO_DL='true'" in env_file.read_text(encoding="utf-8")
    with authed_client() as client:
        again = client.get("/api/config")
        assert again.json()["values"]["FNMUSIC_LYRIC_AUTO_DL"] == "true"


# ------------------------------------------------------------------ 切源动作 ---

def test_provider_switch_stops_old_starts_new(env_file, svctl):
    with authed_client() as client:
        r = client.put("/api/config", json={"values": {
            "FNMUSIC_NETEASE_ENABLED": "false",
            "FNMUSIC_LX_ENABLED": "true",
        }})
        assert r.status_code == 200
        actions = r.json()["actions"]
        assert ("stop", "musicbox") in svctl.calls
        assert ("start", "lxmusic") in svctl.calls
        assert all(a["ok"] for a in actions if a["kind"] == "process")


def test_provider_switch_to_neteasefree(env_file, svctl):
    """第四音源 neteasefree：从 musicbox 切过去时停盒子、起免扫码进程并落盘开关。"""
    with authed_client() as client:
        r = client.put("/api/config", json={"values": {
            "FNMUSIC_NETEASE_ENABLED": "false",
            "FNMUSIC_NETEASEFREE_ENABLED": "true",
        }})
        assert r.status_code == 200
        assert ("stop", "musicbox") in svctl.calls
        assert ("start", "neteasefree") in svctl.calls
    text = env_file.read_text(encoding="utf-8")
    assert "FNMUSIC_NETEASEFREE_ENABLED='true'" in text
    assert "FNMUSIC_NETEASE_ENABLED='false'" in text


def test_neteasefree_schema_registered(env_file):
    with authed_client() as client:
        r = client.get("/api/config")
        assert r.status_code == 200
        meta = r.json()["schema"]["FNMUSIC_NETEASEFREE_ENABLED"]
        assert meta["kind"] == "bool" and meta["reload"] == "process"


# ------------------------------------------------------------------ 音源预览 ---

def _preview_http():
    """预览接口的 healthz 轮询用 MockTransport 直接返回 200。"""
    webui.app.state.http = httpx.AsyncClient(transport=httpx.MockTransport(
        lambda request: httpx.Response(200, json={"ok": True})))


def test_preview_endpoint_starts_unenabled_provider(env_file, svctl):
    """点选未启用的音源卡片：临时拉起进程（不写 .env），注册 5 分钟倒计时。"""
    with authed_client() as client:
        _preview_http()
        r = client.post("/api/preview", json={"provider": "musicdl"})
        assert r.status_code == 200
        body = r.json()
        assert body["ok"] and body["preview"] is True and body["seconds_left"] > 0
        assert ("start", "musicdl") in svctl.calls
        assert "musicdl" in webui._preview_until
        # 已是当前启用的音源（musicbox）：不拉起、不进预览表
        r2 = client.post("/api/preview", json={"provider": "musicbox"})
        assert r2.status_code == 200 and r2.json()["preview"] is False
    assert "FNMUSIC_MUSICDL_ENABLED='false'" in env_file.read_text(encoding="utf-8")


def test_preview_endpoint_starts_neteasefree(env_file, svctl):
    """第四音源 neteasefree 也能走预览临时拉起（点选卡片即时可用）。"""
    with authed_client() as client:
        _preview_http()
        r = client.post("/api/preview", json={"provider": "neteasefree"})
        assert r.status_code == 200
        body = r.json()
        assert body["ok"] and body["preview"] is True
        assert ("start", "neteasefree") in svctl.calls
        assert "neteasefree" in webui._preview_until


def test_preview_endpoint_rejects_unknown_provider(env_file, svctl):
    with authed_client() as client:
        r = client.post("/api/preview", json={"provider": "docker"})
        assert r.status_code == 400
    assert not svctl.calls


def test_preview_reap_stops_expired_promotes_enabled(env_file, svctl):
    """到期清退：未启用的停止进程；已随保存启用的转正（只移出预览表，不停）。"""
    webui._preview_until.update({
        "musicdl": time.monotonic() - 1,   # 未启用且到期 → stop
        "musicbox": time.monotonic() - 1,  # .env 里启用中 → 转正
        "lxmusic": time.monotonic() + 300, # 未到期 → 不动
    })
    stopped = webui.preview_reap()
    assert stopped == ["musicdl"]
    assert ("stop", "musicdl") in svctl.calls
    assert ("stop", "musicbox") not in svctl.calls
    assert set(webui._preview_until) == {"lxmusic"}


def test_preview_reap_stop_failure_keeps_entry_for_retry(env_file, monkeypatch):
    """stop 失败（supervisorctl 抖动）不吞掉预览表项：保留过期 deadline，
    下一轮 reaper 重试；恢复成功后才真正清退——否则预览进程漏停常驻。"""
    calls: list[tuple] = []

    def failing_then_ok(*args, timeout=20.0):
        calls.append(tuple(args))
        if len(calls) <= 1:  # 第一次 stop 失败（如容器重启窗口）
            return 1, "spurious supervisor error"
        return 0, "stopped"

    monkeypatch.setattr(webui, "supervisorctl", failing_then_ok)
    webui._preview_until["musicdl"] = time.monotonic() - 1

    # 第一轮：停止失败——不崩、不计入 stopped、表项保留
    assert webui.preview_reap() == []
    assert "musicdl" in webui._preview_until
    assert calls == [("stop", "musicdl")]

    # 第二轮（reaper 每 15s 一轮）：重试成功，表项清掉
    assert webui.preview_reap() == ["musicdl"]
    assert "musicdl" not in webui._preview_until
    assert calls == [("stop", "musicdl"), ("stop", "musicdl")]


def test_put_config_stops_leftover_preview(env_file, svctl):
    """保存收尾：预览了 musicdl 但最终保存的还是 musicbox → musicdl 立即停止。"""
    webui._preview_until["musicdl"] = time.monotonic() + 300
    with authed_client() as client:
        r = client.put("/api/config", json={"values": {"FNMUSIC_QUALITY_MODE": "balanced"}})
        assert r.status_code == 200
        preview_stops = [a for a in r.json()["actions"] if a.get("preview")]
        assert len(preview_stops) == 1 and preview_stops[0]["program"] == "musicdl"
        assert ("stop", "musicdl") in svctl.calls
    assert "musicdl" not in webui._preview_until


def test_platforms_fetch_renews_preview(env_file, svctl, monkeypatch):
    """预览期间查看平台列表（或测试 lx 源）视为活跃：倒计时续期。"""
    monkeypatch.setitem(webui.CONF, "musicdl_url", "http://md.test")
    webui._preview_until["musicdl"] = time.monotonic() + 1
    webui.app.state.http = httpx.AsyncClient(transport=httpx.MockTransport(
        lambda request: httpx.Response(200, json={"enabled": ["KuwoMusicClient"], "registered": ["KuwoMusicClient"]})))
    with authed_client() as client:
        r = client.get("/api/platforms")
        assert r.status_code == 200
    assert webui._preview_until["musicdl"] - time.monotonic() > 250


def test_musicdl_platform_change_restarts_process(env_file, svctl):
    # 先切到 musicdl
    with authed_client() as client:
        r = client.put("/api/config", json={"values": {
            "FNMUSIC_NETEASE_ENABLED": "false",
            "FNMUSIC_MUSICDL_ENABLED": "true",
            "FNMUSIC_ONLINE_SOURCES": "KuwoMusicClient,MiguMusicClient",
        }})
        assert r.status_code == 200
        svctl.calls.clear()
        # 平台再次变更（provider 不变）→ restart musicdl
        r2 = client.put("/api/config", json={"values": {
            "FNMUSIC_ONLINE_SOURCES": "KuwoMusicClient",
        }})
        assert r2.status_code == 200
        assert ("restart", "musicdl") in svctl.calls
    text = env_file.read_text(encoding="utf-8")
    assert "MUSICDL_SOURCES='KuwoMusicClient'" in text or "MUSICDL_SOURCES" in text


# ------------------------------------------------------------------ lx 换源回路 ---

def test_lx_url_change_verifies_activates_and_derives_sources(env_file, svctl, monkeypatch):
    monkeypatch.setitem(webui.CONF, "lx_url", "http://lx.test")
    hits = {"verify": 0, "activate": 0}

    def handler(request: httpx.Request) -> httpx.Response:
        url = str(request.url)
        if url.endswith("/api/v1/source/verify"):
            hits["verify"] += 1
            assert request.read()  # 携带 body
            return httpx.Response(200, json={"ok": True, "data": {
                "platforms": ["kw", "kg"], "meta": {"name": "t"}, "probe": {"title": "x"},
            }})
        if request.url.host == "lx.test" and request.method == "POST":
            hits["activate"] += 1
            return httpx.Response(200, json={"ok": True, "data": {"url": "https://s/1.js"}})
        return httpx.Response(200, json={"ok": True})

    _mock_http(handler)

    # 切到 lx 并换 URL：verify → 写 env（含推导 LX_SOURCES）→ 起进程 → 激活
    with authed_client() as client:
        r = client.put("/api/config", json={"values": {
            "FNMUSIC_NETEASE_ENABLED": "false",
            "FNMUSIC_LX_ENABLED": "true",
            "LX_SOURCE_URL": "https://s/1.js",
        }})
        assert r.status_code == 200
    assert hits["verify"] == 1
    assert hits["activate"] == 1
    text = env_file.read_text(encoding="utf-8")
    assert "LX_SOURCE_URL='https://s/1.js'" in text
    assert "LX_SOURCES='kw,kg'" in text  # 来自校验报告的可用平台


def test_lx_url_change_blocked_when_verify_fails(env_file, svctl, monkeypatch):
    monkeypatch.setitem(webui.CONF, "lx_url", "http://lx.test")

    def handler(request: httpx.Request) -> httpx.Response:
        if str(request.url).endswith("/api/v1/source/verify"):
            return httpx.Response(200, json={"ok": False, "data": {
                "category": "download", "message": "下载失败: 404",
            }})
        return httpx.Response(200, json={"ok": True})

    _mock_http(handler)
    before = env_file.read_text(encoding="utf-8")
    with authed_client() as client:
        r = client.put("/api/config", json={"values": {
            "FNMUSIC_NETEASE_ENABLED": "false",
            "FNMUSIC_LX_ENABLED": "true",
            "LX_SOURCE_URL": "https://bad/1.js",
        }})
        assert r.status_code == 400
        assert "校验未通过" in r.json()["error"]
    assert env_file.read_text(encoding="utf-8") == before  # 校验失败不落盘


def test_lx_verify_endpoint_survives_non_json_upstream(env_file, monkeypatch):
    """lxmusic 返回裸 500 纯文本（如未捕获异常）时，WebUI 必须转成可读错误而不是自身也 500。"""
    monkeypatch.setitem(webui.CONF, "lx_url", "http://lx.test")

    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(500, text="Internal Server Error")

    _mock_http(handler)
    with authed_client() as client:
        r = client.post("/api/lx/verify", json={"values": {"url": "https://s/1.js"}})
        assert r.status_code == 500
        assert r.json()["ok"] is False
        assert "非 JSON" in r.json()["error"]


def test_lx_verify_accepts_file_url(env_file, monkeypatch):
    """file:// 上传地址必须能进入 verify 链路（透传 lxmusic 服务）。"""
    monkeypatch.setitem(webui.CONF, "lx_url", "http://lx.test")
    captured = {}

    def handler(request: httpx.Request) -> httpx.Response:
        import json as _json
        captured["body"] = _json.loads(request.content)
        return httpx.Response(200, json={"ok": True, "data": {"platforms": ["kw"]}})

    _mock_http(handler)
    with authed_client() as client:
        r = client.post("/api/lx/verify", json={"values": {"url": "file:///data/lxmusic/uploads/x.js"}})
        assert r.status_code == 200
        assert r.json()["ok"] is True
        assert captured["body"]["url"] == "file:///data/lxmusic/uploads/x.js"
        # 非 http/file 协议仍被拒
        r2 = client.post("/api/lx/verify", json={"values": {"url": "ftp://s/1.js"}})
        assert r2.status_code == 400


_VALID_SCRIPT = "/*\n * @name 上传源\n * @version 1.0.0\n */\nconsole.log(1)\n"


def test_lx_upload_proxies_to_lxmusic(env_file, monkeypatch):
    """multipart .js → lxmusic /api/v1/source/upload，返回 file:// URL。"""
    monkeypatch.setitem(webui.CONF, "lx_url", "http://lx.test")
    captured = {}

    def handler(request: httpx.Request) -> httpx.Response:
        captured["path"] = request.url.path
        import json as _json
        captured["body"] = _json.loads(request.content)
        return httpx.Response(200, json={
            "ok": True,
            "data": {"path": "/data/lxmusic/uploads/mine.js",
                     "url": "file:///data/lxmusic/uploads/mine.js",
                     "meta": {"name": "上传源"}},
        })

    _mock_http(handler)
    with authed_client() as client:
        r = client.post("/api/lx/upload",
                        files={"file": ("mine.js", _VALID_SCRIPT.encode(), "text/javascript")})
        assert r.status_code == 200
        body = r.json()
        assert body["ok"] is True
        assert body["data"]["url"] == "file:///data/lxmusic/uploads/mine.js"
        assert captured["path"] == "/api/v1/source/upload"
        assert captured["body"]["filename"] == "mine.js"
        assert captured["body"]["script"] == _VALID_SCRIPT


def test_lx_upload_accepts_json_from_page(env_file, monkeypatch):
    """管理页上传和 NAS 选择都 POST JSON，不能再拒掉非 multipart。"""
    monkeypatch.setitem(webui.CONF, "lx_url", "http://lx.test")
    captured = {}

    def handler(request: httpx.Request) -> httpx.Response:
        import json as _json
        captured["body"] = _json.loads(request.content)
        return httpx.Response(200, json={
            "ok": True,
            "data": {"url": "file:///data/lxmusic/uploads/mine.js", "meta": {"name": "上传源"}},
        })

    _mock_http(handler)
    with authed_client() as client:
        r = client.post("/api/lx/upload", json={"filename": "mine.js", "script": _VALID_SCRIPT})
        assert r.status_code == 200
        assert r.json()["data"]["url"].startswith("file://")
        assert captured["body"]["script"] == _VALID_SCRIPT
        bad = client.post("/api/lx/upload", json={"filename": "a.txt", "script": _VALID_SCRIPT})
        assert bad.status_code == 400


def test_lx_upload_rejects_bad_requests(env_file, monkeypatch):
    monkeypatch.setitem(webui.CONF, "lx_url", "http://lx.test")
    _mock_http(lambda r: httpx.Response(200, json={"ok": True}))
    with authed_client() as client:
        # 非 .js 后缀
        r = client.post("/api/lx/upload", files={"file": ("a.txt", b"hello", "text/plain")})
        assert r.status_code == 400
        # 非 UTF-8
        r2 = client.post("/api/lx/upload", files={"file": ("a.js", b"\xff\xfe", "text/plain")})
        assert r2.status_code == 400
        # 缺 file 字段
        r3 = client.post("/api/lx/upload", data={"x": "1"})
        assert r3.status_code == 400


def test_lx_url_change_save_reports_error_for_non_json_activate(env_file, svctl, monkeypatch):
    """保存时激活 lx 源，上游非 JSON 响应要落到 actions 的 error 字段，而不是让保存接口崩掉。"""
    monkeypatch.setitem(webui.CONF, "lx_url", "http://lx.test")

    def handler(request: httpx.Request) -> httpx.Response:
        url = str(request.url)
        if url.endswith("/api/v1/source/verify"):
            return httpx.Response(200, json={"ok": True, "data": {"platforms": ["kw"]}})
        if url.endswith("/api/v1/source") and request.method == "POST":
            return httpx.Response(500, text="Internal Server Error")
        return httpx.Response(200, json={"ok": True})

    _mock_http(handler)
    with authed_client() as client:
        r = client.put("/api/config", json={"values": {
            "FNMUSIC_NETEASE_ENABLED": "false",
            "FNMUSIC_LX_ENABLED": "true",
            "LX_SOURCE_URL": "https://s/1.js",
        }})
        assert r.status_code == 200
        activate = [a for a in r.json()["actions"] if a["kind"] == "lx_activate"]
        assert activate and activate[0]["ok"] is False
        assert "非 JSON" in activate[0]["error"]


# ------------------------------------------------------------------ status / platforms ---

def test_supervisor_status_parses_despite_nonzero_exit(monkeypatch):
    """按需加载下 status 必有 STOPPED 程序，supervisorctl 退出码 3 是常态而非失败。"""
    monkeypatch.setattr(webui, "supervisorctl", lambda *a, timeout=20.0: (3, (
        "musicdl                        STOPPED   Not started\n"
        "musicbox                       RUNNING   pid 7, uptime 0:01:00\n"
        "lxmusic                        FATAL     Exited too quickly"
    )))
    st = webui.supervisor_status()
    assert st["musicdl"]["state"] == "STOPPED"
    assert st["musicbox"]["state"] == "RUNNING"
    assert st["lxmusic"]["state"] == "FATAL"


def test_supervisor_status_connection_error_returns_empty(monkeypatch):
    monkeypatch.setattr(webui, "supervisorctl",
                        lambda *a, timeout=20.0: (1, "error: <class 'ConnectionRefusedError'>, [Errno 111]"))
    assert webui.supervisor_status() == {}


def test_status_aggregates_processes_and_health(env_file, svctl, monkeypatch):
    monkeypatch.setitem(webui.CONF, "musicdl_url", "http://md.test")
    monkeypatch.setitem(webui.CONF, "musicbox_url", "http://mb.test")
    monkeypatch.setitem(webui.CONF, "lx_url", "http://lx.test")

    def handler(request: httpx.Request) -> httpx.Response:
        host = request.url.host
        if host == "mb.test":
            return httpx.Response(200, json={"ok": True, "service": "musicbox"})
        if host == "lx.test":
            return httpx.Response(200, json={"ok": True, "data": {
                "configured": True, "url": "https://s/1.js", "initialized": True,
                "last_error": "", "source": {"name": "t", "running": True, "platforms": {"kw": {}}},
            }})
        return httpx.Response(500)

    _mock_http(handler)
    # 当前 provider 是 musicbox（BASE_ENV）
    with authed_client() as client:
        r = client.get("/api/status")
        assert r.status_code == 200
        rj = r.json()
        assert rj["version"] == "2.0.0"
        assert rj["current_provider"] == "musicbox"
        assert rj["processes"]["musicbox"]["state"] == "RUNNING"
        assert rj["processes"]["lxmusic"]["state"] == "STOPPED"
        assert rj["services"]["musicbox"]["reachable"] is True
        assert rj["services"]["lxmusic"]["note"]  # 未启用提示
        assert rj["lx_source"] is None


def test_platforms_from_musicdl(env_file, monkeypatch):
    monkeypatch.setitem(webui.CONF, "musicdl_url", "http://md.test")
    _mock_http(lambda r: httpx.Response(200, json={
        "enabled": ["KuwoMusicClient"], "registered": ["BaiduMusicClient", "KuwoMusicClient"],
    }))
    with authed_client() as client:
        r = client.get("/api/platforms")
        assert r.status_code == 200
        rj = r.json()
        assert rj["enabled"] == ["KuwoMusicClient"]
        assert "BaiduMusicClient" in rj["registered"]


def test_platforms_unreachable_503(env_file):
    def handler(request):
        return httpx.Response(502)

    _mock_http(handler)
    with authed_client() as client:
        r = client.get("/api/platforms")
        assert r.status_code == 503
        assert "hint" in r.json()


# ------------------------------------------------------------------ 网易反代/二维码 ---

# webui 反代对 musicbox /api/v1/auth/* 的透传契约：{ok, data:{...}} 信封结构原样透传。
# 前端 static/app.js pollQr/checkQrStatus 按 data.code 解析扫码状态码（历史契约）。
NETEASE_LOGIN_ENVELOPE = {"ok": True, "data": {"unikey": "KEY1", "qr_ascii": "QR",
                                               "qr_url": "https://music.163.com/login?codekey=KEY1"}}
NETEASE_CHECK_ENVELOPE = {"ok": True, "data": {"code": 801, "message": "等待扫码"}}
NETEASE_STATUS_ENVELOPE = {"ok": True, "data": {"logged_in": False}}


def test_netease_auth_proxy_passthrough(env_file, monkeypatch):
    monkeypatch.setitem(webui.CONF, "musicbox_url", "http://mb.test")
    hits = {}

    def handler(request: httpx.Request) -> httpx.Response:
        path = request.url.path
        hits[path] = dict(request.url.params)
        if path == "/api/v1/auth/login":
            return httpx.Response(200, json=NETEASE_LOGIN_ENVELOPE)
        if path == "/api/v1/auth/login/check":
            return httpx.Response(200, json=NETEASE_CHECK_ENVELOPE)
        if path == "/api/v1/auth/status":
            return httpx.Response(200, json=NETEASE_STATUS_ENVELOPE)
        return httpx.Response(404)

    _mock_http(handler)
    with authed_client() as client:
        r = client.post("/api/netease/auth/login")
        assert r.status_code == 200 and r.json()["data"]["unikey"] == "KEY1"
        r2 = client.get("/api/netease/auth/login/check", params={"unikey": "KEY1"})
        # 信封结构原样透传：code 必须在 data 里（前端据此解析，回归见 test_app_js.py）
        assert r2.status_code == 200 and r2.json()["data"]["code"] == 801
        assert hits["/api/v1/auth/login/check"]["unikey"] == "KEY1"  # 查询串透传
        r4 = client.get("/api/netease/auth/status")
        assert r4.status_code == 200 and r4.json()["data"]["logged_in"] is False
        r3 = client.get("/api/netease/auth/evil")
        assert r3.status_code == 404  # 白名单外


def test_netease_auth_proxy_upstream_errors(env_file, monkeypatch):
    monkeypatch.setitem(webui.CONF, "musicbox_url", "http://mb.test")
    # 上游非 2xx：状态码原样透传（前端轮询把非 2xx 当瞬时失败静默重试）
    _mock_http(lambda r: httpx.Response(500))
    with authed_client() as client:
        r = client.get("/api/netease/auth/login/check", params={"unikey": "KEY1"})
        assert r.status_code == 500
    # 上游不可达（连接失败）：统一 502 + detail 提示
    _mock_http(lambda r: (_ for _ in ()).throw(httpx.ConnectError("refused")))
    with authed_client() as client:
        r = client.get("/api/netease/auth/login/check", params={"unikey": "KEY1"})
        assert r.status_code == 502
        assert "musicbox" in r.json()["detail"]


def test_neteasefree_status_proxies_auth_status(env_file, monkeypatch):
    """网易云·免扫码状态：反代 neteasefree /api/v1/auth/status（服务端登录态，只读）。"""
    monkeypatch.setitem(webui.CONF, "neteasefree_url", "http://nf.test")
    captured = {}

    def handler(request: httpx.Request) -> httpx.Response:
        captured["path"] = request.url.path
        return httpx.Response(200, json={"ok": True, "data": {
            "logged_in": True, "nickname": "服务端账号", "user_id": 0,
            "mode": "server_side", "api_base": "https://zm.wwoyun.cn",
        }})

    _mock_http(handler)
    with authed_client() as client:
        r = client.get("/api/neteasefree/status")
        assert r.status_code == 200
        assert captured["path"] == "/api/v1/auth/status"
        data = r.json()["data"]
        assert data["logged_in"] is True and data["mode"] == "server_side"


def test_neteasefree_status_unreachable(env_file, monkeypatch):
    monkeypatch.setitem(webui.CONF, "neteasefree_url", "http://nf.test")
    _mock_http(lambda r: (_ for _ in ()).throw(httpx.ConnectError("refused")))
    with authed_client() as client:
        r = client.get("/api/neteasefree/status")
        assert r.status_code == 200
        assert r.json()["ok"] is False
        assert r.json()["data"] == {}


def test_netease_qr_svg(env_file):
    qrcode = pytest.importorskip("qrcode")
    with authed_client() as client:
        r = client.get("/api/netease/qr", params={"unikey": "KEY1"})
        assert r.status_code == 200
        assert r.headers["content-type"].startswith("image/svg+xml")
        assert b"svg" in r.content
        assert client.get("/api/netease/qr").status_code == 422  # 缺 unikey


# ------------------------------------------------------------------ 静态首页 ---

def test_index_served():
    with TestClient(webui.app) as client:
        r = client.get("/")
        assert r.status_code == 200
        assert "fnmusic-ext" in r.text
        assert "text/html" in r.headers["content-type"]
        assert "/static/icon.png" in r.text
        icon = client.get("/static/icon.png")
        assert icon.status_code == 200
        assert icon.content[:8] == b"\x89PNG\r\n\x1a\n"
        # 桌面网关把整段 /app/fnmusic-ext 前缀转到这里
        via_desktop = client.get("/app/fnmusic-ext/")
        assert via_desktop.status_code == 200
        assert "/app/fnmusic-ext/static/app.js" in via_desktop.text
        assert client.get("/app/fnmusic-ext/static/icon.png").status_code == 200


def test_static_and_index_no_cache():
    """首页与静态资源带 no-cache，避免升级后浏览器仍用旧前端导致版本错配。"""
    with TestClient(webui.app) as client:
        assert client.get("/").headers.get("cache-control") == "no-cache"
        assert client.get("/static/app.js").headers.get("cache-control") == "no-cache"
        # 带桌面前缀同样生效（中间件先剥前缀）
        assert client.get("/app/fnmusic-ext/static/style.css").headers.get("cache-control") == "no-cache"


def test_netease_my_playlists_defaults_and_saves(env_file):
    with authed_client() as client:
        view = client.get("/api/config")
        assert view.status_code == 200
        # 默认关闭；schema 元数据齐备（hot 热重载）
        assert view.json()["values"]["FNMUSIC_NETEASE_MY_PLAYLISTS"] == "false"
        meta = view.json()["schema"]["FNMUSIC_NETEASE_MY_PLAYLISTS"]
        assert meta["kind"] == "bool" and meta["reload"] == "hot"
        saved = client.put("/api/config", json={"values": {"FNMUSIC_NETEASE_MY_PLAYLISTS": True}})
        assert saved.status_code == 200
        assert "FNMUSIC_NETEASE_MY_PLAYLISTS" in saved.json()["changed"]
        assert saved.json()["actions"] == []  # 热键无进程动作
    assert "FNMUSIC_NETEASE_MY_PLAYLISTS='true'" in env_file.read_text(encoding="utf-8")
    with authed_client() as client:
        again = client.get("/api/config")
        assert again.json()["values"]["FNMUSIC_NETEASE_MY_PLAYLISTS"] == "true"


# ------------------------------------------------------- 自定义歌单 / 关于 ---

M3U_SAMPLE = """#EXTM3U
#EXTINF:-1,周杰伦 - 晴天
/music/周杰伦 - 晴天.mp3
#EXTINF:-1,林俊杰 - 江南
/music/林俊杰 - 江南.flac
"""


def test_custom_playlist_crud(env_file, tmp_path, monkeypatch):
    if webui.dailyrec is None:
        pytest.skip("proxy/recommend.py 不可用")
    monkeypatch.setenv("FNMUSIC_CUSTOM_PLAYLIST_DIR", str(tmp_path / "custom_playlists"))
    with authed_client() as client:
        empty = client.get("/api/custom-playlists")
        assert empty.status_code == 200
        assert empty.json()["playlists"] == []
        assert empty.json()["supported_exts"] == ["m3u", "m3u8", "pls", "cue"]

        created = client.post(
            "/api/custom-playlists",
            json={"name": "我的歌单", "mode": "file", "filename": "test.m3u", "text": M3U_SAMPLE},
        )
        assert created.status_code == 200, created.text
        pl = created.json()["playlist"]
        assert pl["name"] == "我的歌单"
        assert pl["entryCount"] == 2
        assert pl["format"] == "m3u"
        assert pl["enabled"] is True
        pid = pl["id"]
        assert pid

        listed = client.get("/api/custom-playlists").json()["playlists"]
        assert len(listed) == 1 and listed[0]["id"] == pid

        # 关闭（热重载：enabled 落盘）
        off = client.put(f"/api/custom-playlists/{pid}", json={"enabled": False})
        assert off.status_code == 200
        assert off.json()["playlist"]["enabled"] is False

        # 删除
        assert client.delete(f"/api/custom-playlists/{pid}").json()["ok"] is True
        assert client.get("/api/custom-playlists").json()["playlists"] == []


def test_custom_playlist_validation(env_file, tmp_path, monkeypatch):
    if webui.dailyrec is None:
        pytest.skip("proxy/recommend.py 不可用")
    monkeypatch.setenv("FNMUSIC_CUSTOM_PLAYLIST_DIR", str(tmp_path / "custom_playlists"))
    with authed_client() as client:
        # 大模型点歌缺提示 → 400
        assert client.post("/api/custom-playlists", json={"mode": "llm"}).status_code == 400
        # 导入模式未提供内容 → 400
        assert client.post("/api/custom-playlists", json={"mode": "file"}).status_code == 400
        # 更新不存在的歌单 → 404
        assert client.put("/api/custom-playlists/nope", json={"enabled": False}).status_code == 404
        # 删除不存在的歌单 → 404
        assert client.delete("/api/custom-playlists/nope").status_code == 404


def test_about_and_update_detection(env_file, monkeypatch):
    with authed_client() as client:
        about = client.get("/api/about")
        assert about.status_code == 200
        body = about.json()
        assert body["version"] == "2.0.0"
        assert "github.com" in body["repo_url"]
        assert body["update_url"].endswith("update.json")
        assert any("gh-proxy.com" in p for p in body["update_proxies"])

    async def fake_fetch(request, url, *, timeout=4.0):
        return True, {"version": "3.0.0", "date": "2026-10-07", "notes": "新版本"}

    monkeypatch.setattr(webui, "_fetch_json", fake_fetch)
    with authed_client() as client:
        r = client.get("/api/about/update").json()
        assert r["ok"] is True
        assert r["updateAvailable"] is True
        assert r["latest"]["version"] == "3.0.0"
        assert r["latest"]["notes"] == "新版本"

    async def same_fetch(request, url, *, timeout=4.0):
        return True, {"version": "2.0.0", "notes": ""}

    monkeypatch.setattr(webui, "_fetch_json", same_fetch)
    with authed_client() as client:
        assert client.get("/api/about/update").json()["updateAvailable"] is False

    async def fail_fetch(request, url, *, timeout=4.0):
        return False, {"error": "网络不可达"}

    monkeypatch.setattr(webui, "_fetch_json", fail_fetch)
    with authed_client() as client:
        bad = client.get("/api/about/update").json()
        assert bad["ok"] is False
        assert "网络不可达" in bad["error"]


def test_about_update_falls_back_to_proxy(env_file, monkeypatch):
    """直连 GitHub 失败时，自动回退到 gh-proxy 加速代理取 update.json。"""
    seen: list[str] = []

    async def fake_fetch(request, url, *, timeout=4.0):
        seen.append(url)
        if url.startswith("https://raw.githubusercontent.com"):
            return False, {"error": "直连超时"}
        return True, {"version": "3.0.0", "notes": "n"}

    monkeypatch.setattr(webui, "_fetch_json", fake_fetch)
    with authed_client() as client:
        r = client.get("/api/about/update").json()
    assert r["ok"] is True and r["updateAvailable"] is True
    assert seen[0].startswith("https://raw.githubusercontent.com")
    assert seen[1].startswith("https://gh-proxy.com/https://raw.githubusercontent.com")

    # 代理也失败 → 返回失败并带上最后一次错误
    async def all_fail(request, url, *, timeout=4.0):
        return False, {"error": "全部不可达"}

    monkeypatch.setattr(webui, "_fetch_json", all_fail)
    with authed_client() as client:
        bad = client.get("/api/about/update").json()
    assert bad["ok"] is False and "全部不可达" in bad["error"]


def test_update_manifest_matches_version():
    """仓库根 update.json 的版本号应与 VERSION 一致（发版自检）。"""
    import json

    repo_root = HERE.parent
    version = (repo_root / "VERSION").read_text(encoding="utf-8").strip()
    manifest = json.loads((repo_root / "update.json").read_text(encoding="utf-8"))
    assert manifest["version"] == version
    assert manifest.get("notes")


# ------------------------------------------------------------------ 网关管理员 ---

def test_api_requires_admin(env_file):
    with TestClient(webui.app) as client:
        for path in ("/api/config", "/api/preview", "/api/lx/upload"):
            denied = client.get(path) if path == "/api/config" else client.post(path, json={})
            assert denied.status_code == 403, path
            assert denied.json()["error"] == "需要管理员"
        guest = client.get("/api/config", headers={"X-Trim-Isadmin": "false"})
        assert guest.status_code == 403
        assert client.get("/healthz").json() == {"ok": True}
        assert client.get("/").status_code == 200
    with authed_client() as client:
        saved = client.put("/api/config", json={"values": {"FNMUSIC_QUALITY_MODE": "smooth"}})
        assert saved.status_code == 200
    assert "FNMUSIC_QUALITY_MODE='smooth'" in env_file.read_text(encoding="utf-8")
